# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('handler', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Intent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.App')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
                ('require', models.BooleanField(default=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Intent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='intent',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Skill'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Intent'),
        ),
    ]
